import { test, expect } from './fixtures.js';

test('administrator saves three image roles, persists settings and restores built-in artwork', async ({ page }, info) => {
  await page.goto('/login');
  await page.getByLabel('用户名').fill('stage7_admin');
  await page.getByLabel('密码', { exact: true }).fill('stage two password');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.locator('a.game-card[href="/games/splendor.base/1.0.0"]')).toBeVisible();
  await page.locator('.nav-tools summary').click();
  await page.getByRole('link', { name: '管理员后台', exact: true }).click();
  await expect(page.getByRole('heading', { name: '管理员后台', exact: true })).toBeVisible();
  await page.getByRole('link', { name: '游戏展示', exact: true }).click();
  await page.getByLabel('配置游戏').selectOption('splendor.base@1.0.0');
  await page.getByLabel('游戏图标地址').fill('data:image/svg+xml,invalid');
  await page.getByRole('button', { name: '保存展示图片' }).click();
  await expect(page.getByRole('alert')).toContainText('公开 HTTPS');
  await page.getByRole('button', { name: '重新加载配置' }).click();
  await expect(page.getByLabel('配置游戏')).toHaveValue('splendor.base@1.0.0');
  await expect(page.getByLabel('游戏图标地址')).toHaveValue('');
  await page.getByLabel('游戏图标地址').fill('/game-art/color-match-icon.svg');
  await page.getByLabel('大厅封面地址').fill('/game-art/grid-garden.svg');
  await page.getByLabel('详情背景地址').fill('/game-art/counter.svg');
  await page.getByRole('button', { name: '保存展示图片' }).click();
  await expect(page.getByRole('status')).toContainText('展示图片已保存');
  await page.reload();
  await page.getByLabel('配置游戏').selectOption('splendor.base@1.0.0');
  await expect(page.getByLabel('游戏图标地址')).toHaveValue('/game-art/color-match-icon.svg');
  await expect(page.getByLabel('大厅封面地址')).toHaveValue('/game-art/grid-garden.svg');
  await expect(page.getByLabel('详情背景地址')).toHaveValue('/game-art/counter.svg');
  await page.screenshot({ path: info.outputPath('presentation-admin.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await page.getByRole('link', { name: '游戏大厅', exact: true }).click();
  const card = page.locator('a.game-card[href="/games/splendor.base/1.0.0"]');
  await expect(card.locator('.game-cover img')).toHaveAttribute('src', '/game-art/grid-garden.svg');
  await expect(card.locator('.game-card-icon img')).toHaveAttribute('src', '/game-art/color-match-icon.svg');
  await card.click();
  await expect(page.getByRole('heading', { name: '公开房间', exact: true })).toBeVisible();
  await expect(page.locator('.game-detail-icon img')).toHaveAttribute('src', '/game-art/color-match-icon.svg');
  await expect(page.locator('.game-banner-background img')).toHaveAttribute('src', '/game-art/counter.svg');
  await page.route('**/game-art/color-match-icon.svg', route => route.abort());
  await page.reload();
  await expect(page.locator('.game-detail-icon .game-art-fallback')).toBeVisible();
  await expect(page.getByRole('link', { name: '创建房间', exact: true })).toBeVisible();
  await page.unroute('**/game-art/color-match-icon.svg');
  await page.goto('/admin/games');
  await page.getByLabel('配置游戏').selectOption('splendor.base@1.0.0');
  await page.getByRole('button', { name: '使用内置图片' }).click();
  await page.getByRole('button', { name: '保存展示图片' }).click();
  await expect(page.getByRole('status')).toContainText('展示图片已保存');
  await page.goto('/games/splendor.base/1.0.0');
  await expect(page.locator('.game-detail-icon img')).toHaveAttribute('src', '/game-art/splendor-icon.svg');
});

test('ordinary accounts cannot edit game presentation', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('用户名').fill('stage3_a');
  await page.getByLabel('密码', { exact: true }).fill('stage two password');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('heading', { name: '游戏大厅', exact: true })).toBeVisible();
  await page.goto('/admin/games');
  await expect(page.getByText('请使用管理员账户登录后访问后台。')).toBeVisible();
  await expect(page.getByRole('button', { name: '保存展示图片' })).toHaveCount(0);
});
