import { expect, test, openRoomCreation } from './fixtures.js';

test('room host adds and edits model AI, restores settings and plays to completion', async ({ page }) => {
  test.setTimeout(90000);
  await page.goto('/login');
  await page.getByLabel('用户名').fill('stage3_a');
  await page.getByLabel('密码').fill('stage two password');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('heading', { name: '游戏大厅' })).toBeVisible();
  await openRoomCreation(page);
  await page.getByLabel('房间名').fill('可配置模型 AI');
  await page.getByRole('button', { name: '创建并生成邀请码' }).click();
  await expect(page.getByRole('heading', { name: '可配置模型 AI' })).toBeVisible();
  const roomUrl = page.url();
  const emptySeat = page.locator('.seat-card').nth(1);
  await emptySeat.getByText('选择模型 AI', { exact: true }).click();
  await expect(emptySeat.getByRole('button', { name: '添加模型 AI', exact: true })).toBeDisabled();
  await emptySeat.getByRole('link', { name: '管理模型配置' }).click();
  await expect(page.getByRole('heading', { name: '模型配置' })).toBeVisible();
  await page.getByLabel('配置名称').fill('房间模拟模型');
  await page.getByLabel('服务端点').selectOption('mock');
  await page.getByLabel('模型标识').fill('mock-v1');
  await page.getByRole('button', { name: '保存配置', exact: true }).click();
  await expect(page.getByRole('heading', { name: '房间模拟模型', exact: true })).toBeVisible();
  await page.goto(roomUrl);
  await emptySeat.getByText('选择模型 AI', { exact: true }).click();
  await expect(emptySeat.getByLabel('模型配置')).toContainText('房间模拟模型');
  await emptySeat.getByRole('button', { name: '添加模型 AI', exact: true }).click();
  await expect(emptySeat.getByText('模型 AI · 已就绪', { exact: true })).toBeVisible();
  await page.reload();
  await expect(emptySeat.getByText('模型 AI · 已就绪', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '准备', exact: true }).click();
  await expect(page.getByRole('button', { name: '取消准备', exact: true })).toBeVisible();
  await emptySeat.getByText('AI 设置', { exact: true }).click();
  await expect(emptySeat.getByLabel('AI 类型')).toHaveValue('model');
  await emptySeat.getByLabel('AI 类型').selectOption('script');
  await emptySeat.getByRole('button', { name: '保存 AI 设置' }).click();
  await expect(emptySeat.getByText('脚本 AI · 已就绪', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '准备', exact: true })).toBeVisible();
  await emptySeat.getByText('AI 设置', { exact: true }).click();
  await emptySeat.getByLabel('AI 类型').selectOption('model');
  await emptySeat.getByRole('button', { name: '保存 AI 设置' }).click();
  await expect(emptySeat.getByText('模型 AI · 已就绪', { exact: true })).toBeVisible();
  await emptySeat.getByText('AI 设置', { exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('model-bot-settings.png'), fullPage: true });
  await page.getByRole('button', { name: '准备', exact: true }).click();
  await page.getByRole('button', { name: '开始游戏' }).click();
  await expect(page.getByRole('heading', { name: 'Color Match', exact: true })).toBeVisible();
  await expect(page.getByText(/座位 2 · 模型 AI/)).toBeVisible();
  await page.locator('.controller-panel summary').click();
  await page.getByRole('button', { name: '启用模型 · 房间模拟模型' }).click();
  await expect(page).toHaveURL(/\/rooms\//, { timeout: 60000 });
  await expect(page.getByRole('heading', { name: '本局已结束，已返回房间' })).toBeVisible();
  await expect(emptySeat.getByText('模型 AI · 已就绪', { exact: true })).toBeVisible();
  await expect(page.getByRole('alert')).toHaveCount(0);
});
