import {expect,test} from './fixtures.js';

test('host plays a human seat alongside script AI without human script delegation',async({page})=>{
  test.setTimeout(90_000);
  await page.goto('/login');
  await page.getByLabel('用户名').fill('stage3_a');
  await page.getByLabel('密码').fill('stage two password');
  await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page.getByRole('heading',{name:'游戏大厅'})).toBeVisible();
  await page.getByRole('link',{name:'创建房间'}).click();
  const games=page.getByLabel('游戏与版本');
  await expect(games).toContainText('Color Match');
  await games.selectOption('color-match@1.0.0');
  await page.getByLabel('房间名').fill(`AI 验收 ${test.info().project.name}`);
  await page.getByRole('button',{name:'创建并生成邀请码'}).click();
  await page.getByRole('button',{name:'添加脚本 AI'}).click();
  await expect(page.getByText('脚本 AI · basic-v1 · 已就绪')).toBeVisible();
  await page.getByRole('button',{name:'准备',exact:true}).click();
  await expect(page.getByRole('button',{name:'开始游戏'})).toBeEnabled();
  await page.getByRole('button',{name:'开始游戏'}).click();
  await expect(page.getByRole('heading',{name:'Color Match',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'开启脚本托管'})).toHaveCount(0);
  await page.locator('.controller-panel summary').click();
  await expect(page.getByText('由你操作',{exact:true})).toBeVisible();
  await expect(page.getByText(/座位 2 · 脚本 AI/)).toBeVisible();
  await page.getByRole('button',{name:'返回房间'}).click();
  await expect(page.getByText('实时同步',{exact:true})).toBeVisible();
  await expect(page).toHaveURL(/\/rooms\//);
  await expect(page.getByRole('button',{name:'退出房间'})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'强制关闭房间',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'进入对局'}).click();
  await expect(page.getByRole('heading',{name:'Color Match',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
});
