import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import * as argon2 from 'argon2';
import { z } from 'zod';
import { createDatabase } from '../apps/api/src/db/index.js';
import { createAccount, displayNameSchema, passwordSchema, usernameSchema } from '../apps/api/src/auth.js';

const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL is required');const db=createDatabase(url);
async function secret(){if(stdin.isTTY)throw new Error('Pass the password through stdin; interactive echo is disabled for safety');const rl=createInterface({input:stdin,output:stdout});try{return await rl.question('');}finally{rl.close();}}
const [command,usernameRaw,displayNameRaw]=process.argv.slice(2); const username=usernameRaw?usernameSchema.parse(usernameRaw).toLowerCase():undefined;
try{
  if(command==='admin:init'){if(!username)throw new Error('Usage: admin:init <username> [displayName], with password on stdin');const exists=await db.query("SELECT 1 FROM accounts WHERE role='administrator' LIMIT 1");if(exists.rowCount){console.log('administrator already exists; unchanged');}else{const password=passwordSchema.parse(await secret());await createAccount(db,{username,displayName:displayNameSchema.parse(displayNameRaw??username),password,role:'administrator'});console.log(`created administrator ${username}`);}}
  else if(command==='account:create'){if(!username)throw new Error('Usage: account:create <username> [displayName], with password on stdin');const password=passwordSchema.parse(await secret());await createAccount(db,{username,displayName:displayNameSchema.parse(displayNameRaw??username),password,role:'user'});console.log(`created account ${username}`);}
  else if(command==='account:reset-password'){if(!username)throw new Error('Usage: account:reset-password <username>, with password on stdin');const password=passwordSchema.parse(await secret());const hash=await argon2.hash(password,{type:argon2.argon2id});const client=await db.connect();try{await client.query('BEGIN');const changed=await client.query<{id:string}>('UPDATE accounts SET password_hash=$1 WHERE username_canonical=$2 RETURNING id',[hash,username]);if(!changed.rowCount)throw new Error('Account not found');await client.query('UPDATE sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE account_id=$1',[changed.rows[0]!.id]);await client.query("SELECT pg_notify('boardgame_session_revoked',$1)",[changed.rows[0]!.id]);await client.query('COMMIT');console.log(`reset password and revoked sessions for ${username}`);}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  else if(command==='account:disable'||command==='account:enable'){if(!username)throw new Error(`Usage: ${command} <username>`);const status=command.endsWith('disable')?'disabled':'active';const client=await db.connect();try{await client.query('BEGIN');const changed=await client.query<{id:string}>('UPDATE accounts SET status=$1 WHERE username_canonical=$2 RETURNING id',[status,username]);if(!changed.rowCount)throw new Error('Account not found');if(status==='disabled'){await client.query('UPDATE sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE account_id=$1',[changed.rows[0]!.id]);await client.query("SELECT pg_notify('boardgame_session_revoked',$1)",[changed.rows[0]!.id]);}await client.query('COMMIT');console.log(`${status} account ${username}`);}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  else throw new Error('Commands: admin:init, account:create, account:reset-password, account:disable, account:enable');
}catch(error){if(error instanceof z.ZodError)console.error('Invalid account input:',error.issues.map(i=>i.message).join('; '));else console.error(error instanceof Error?error.message:error);process.exitCode=1;}finally{await db.end();}
